// Generate TypeScript request/response types from the vendored Core schemas
// (packages/protocol/schemas/, a pinned copy of ../valyria/docs/protocol/ at
// core.lock.json's git_rev). Output is git-committed so `npm install` alone
// does not silently change the wire contract — a Core bump regenerates it in a
// deliberate PR (docs/INTEGRATION.md §3).
//
//   node scripts/codegen.mjs

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");
const outDir = join(here, "..", "src", "generated");

const BANNER = `/* GENERATED by scripts/codegen.mjs from packages/protocol/schemas/.
 * Do not edit. Regenerate on a Core bump (see docs/INTEGRATION.md §3). */\n`;

const targets = [
  { schema: "request.schema.json", out: "request.ts", name: "Request" },
  { schema: "response.schema.json", out: "response.ts", name: "Response" },
  { schema: "event.schema.json", out: "event.ts", name: "WireEventEnvelope" },
];

await mkdir(outDir, { recursive: true });

for (const t of targets) {
  const raw = await readFile(join(schemasDir, t.schema), "utf8");
  const schema = JSON.parse(raw);
  const ts = await compile(schema, t.name, {
    bannerComment: BANNER,
    additionalProperties: false,
    style: { singleQuote: false },
  });
  await writeFile(join(outDir, t.out), ts);
  console.log(`codegen: ${t.schema} -> src/generated/${t.out}`);
}

const version = (await readFile(join(schemasDir, "version.txt"), "utf8")).trim();
await writeFile(
  join(outDir, "version.ts"),
  `${BANNER}export const PROTOCOL_VERSION = ${JSON.stringify(version)} as const;\n`,
);
console.log(`codegen: version.txt -> src/generated/version.ts (${version})`);
